name: thinking_capp
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
version: 1.0.0+1

environment:
  sdk: '>=2.17.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^2.1.1
  firebase_auth: ^4.1.1
  firebase_storage: ^11.0.4
  cloud_firestore: ^4.0.4
  algolia: ^1.1.1

  get: ^4.6.5
  image_picker: ^0.8.6
  cached_network_image: ^3.2.1
  flutter_image_compress: ^1.1.3
  photo_view: ^0.14.0
  url_launcher: ^6.1.6
  path_provider: ^2.0.11

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: DM Sans
      fonts:
        - asset: assets/fonts/DMSans-Regular.ttf
        - asset: assets/fonts/DMSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/DMSans-Bold.ttf
          weight: 700
